Improved development scripts (release, etc.)

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,7 +1,22 @@
 #!/bin/bash
 
-## Check for file names with non-ascii characters.
-## From pre-commit.sample
+# ------------------------------------------------------------------------------
+# Check for errors in the Python code.
+# Based on http://www.sitepoint.com/git-hooks-fun-profit/
+git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
+if [[ ${FILE: -3} == ".py" ]]; then
+    python -m py_compile "$FILE" 1> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "Aborting commit due to errors in Python code" >&2
+        exit 1
+    fi
+fi
+done
+
+#-------------------------------------------------------------------------------
+# Check for file names with non-ascii characters.
+# From pre-commit.sample
+
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
 	against=HEAD
@@ -10,7 +25,7 @@ else
 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-# If you want to allow non-ascii filenames set this variable to true.
+# If you want to allow non-ascii filenames, set this variable to true.
 allownonascii=$(git config hooks.allownonascii)
 
 # Cross platform projects tend to avoid non-ascii filenames; prevent
@@ -37,16 +52,3 @@ then
 	echo
 	exit 1
 fi
-
-
-## Check for errors in the Python code.
-## Based on http://www.sitepoint.com/git-hooks-fun-profit/
-git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
-if [[ ${FILE: -3} == ".py" ]]; then
-    python -m py_compile "$FILE" 1> /dev/null
-    if [ $? -ne 0 ]; then
-        echo "Aborting commit due to errors in Python code" >&2
-        exit 1
-    fi
-fi
-done
